roles:
- src: geerlingguy.postgresql

- name: green.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb

collections:
- name: community.postgresql




# WARNING: The scripts ansible, ansible-config, ansible-connection, ansible-console, ansible-doc, ansible-galaxy, ansible-inventory, ansible-playbook, ansible-pull and ansible-vault are installed in '/home/emil/.local/bin' which is not on PATH.
#   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
#   WARNING: The script ansible-community is installed in '/home/emil/.local/bin' which is not on PATH.
#   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


# $HOME/.local/bin